### ISSUE TITLE
Not working with latest `vim-mode`

### ISSUE THREAD

**Issue by meleyal** [gepoch/vim-surround#27] opened 2015-07-23 11:50 UTC
Since updating to `vim-mode` 0.57.0 surround no longer seems to be working.

**Comment by gepoch** [comment] 2015-07-23 15:10
Hmmm... I'm not able to reproduce this.

I'm using

- vim-mode 0.57.0
- vim-surround 0.7.2

Any chance a reload fixes this?

**Comment by meleyal** [comment] 2015-07-23 16:00
Reload didn't fix it. When I try `cs ' "` the whole line is deleted :(

**Comment by gepoch** [comment] 2015-07-23 17:53
Ah! I was investigating the `s '` commands.

This is definitely not working right. Thanks for the ticket.

**Comment by lettertwo** [comment] 2015-07-24 15:37
I *think* this may be caused by the recent change in naming from ['command-mode' to 'normal-mode'][1]. I'm just guessing, but lots of my other vim-specific keybindings recently went haywire as a result of that change. I fixed, of course, by updating to use `.normal-mode` wherever i was previous selecting for `.command-mode`.

[1]: https://github.com/atom/vim-mode/blob/master/CHANGELOG.md#056

**Comment by gepoch** [comment] 2015-07-24 15:43
That's definitely pretty suspicious.

I think I should have some time to get this fixed this weekend. This is a pretty major problem.

**Comment by lettertwo** [comment] 2015-07-24 15:47
:+1: I think the fact that the `s '` commands still work is a good indicator that the keybindings are likely at fault–`.visual-mode` didn't get renamed, so those bindings would be unaffected by the name change.

**Comment by gepoch** [comment] 2015-07-25 22:35
Fixed in v0.7.4!

You were spot on, @lettertwo. Thanks!

**Closed by gepoch** 2015-07-25 22:35 UTC

**Comment by lettertwo** [comment] 2015-07-26 15:03
Excellent! working like a charm.

**Comment by meleyal** [comment] 2015-07-27 08:55
Thanks :)

**Comment by raiscui** [comment] 2016-02-02 03:41
I have same problem :`When I try `cs ' "` the whole line is deleted :(`
